"""'d'

Revision ID: 327b998e3f75
Revises: 4ea10209743f
Create Date: 2019-09-17 20:16:28.983499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327b998e3f75'
down_revision = '4ea10209743f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
